### ISSUE TITLE
Undefined constant ::Formater

### ISSUE THREAD

**Issue by svs** [evandrojr/awesome_print.cr#3]
```
Error in line 1: while requiring "./spec/search_query_spec.cr"

in spec/search_query_spec.cr:8: instantiating 'ap(Array(Int32))'

    ap [1,2,3]
    ^~

in lib/awesome_print/src/awesome_print.cr:5: undefined constant ::Formater

  r = ::Formater.selector(v)
      ^~~~~~~~~~
```

**Comment by evandrojr** [comment]
Hi @svs sorry for the delay. I missed the email about this issue and only found it here by accident after a year.

This error was fixed in github but not at the released shard. I forgot the create a new release in github. It has been fixed, finally.

Thank you very much for your feedback!
